### ISSUE TITLE
tlc.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#50] opened 2017-09-02 19:49 UTC
0.0.0.0 tlc.com

TLC is an American basic cable and satellite television network that is owned by Discovery Communications. Initially focused on educational and learning content, by the late 1990s, the network began to primarily focus towards reality series involving lifestyles, family life, and personal stories.

As of February 2015, approximately 95 million American households (81.6% of households with cable television) receive TLC,[1] although this does not indicate TLC's viewership as of February 2016.

**Comment by mitchellkrogza** [comment] 2017-09-04 11:56
Thanks @xxcriticxx this will be fixed in next push of RAW files, probably around Wednesday this week. 

I've developed a new central repository of dead-domains, re-active-domains, whitelisted-domains and false-positive-domains which will serve as a central de-facto list for when the hosts file is built. 

This will stop ANY false positive or whitelisted domain from ever being re-added by mistake and will make curation of this repo going forward so much easier and also Fool and Fail proof. This is especially needed as I pull fresh data in on rebuilds which is where things like money.cnn.com kept getting re-added. This centralized repo will stop that from every happening again for good.

Still lots in the pipeline and I appreciate all your help finding false positives 👍 

I think my next push of RAW files on wednesday will strip a good amount of dead domains out.

**Comment by xxcriticxx** [comment] 2017-09-04 13:56
@mitchellkrogza just let me know when its ready i will pull new list

**Comment by mitchellkrogza** [comment] 2017-09-04 13:58
@xxcriticxx 👍 will definitely notify you.

**Comment by mitchellkrogza** [comment] 2017-09-05 16:14
@xxcriticxx we have finally reached the letter "t" on the funceble testing for dead / inactive domains so I estimate another day and a half and it should be finally finished and then I will push out some fresh RAW links for you.

**Comment by xxcriticxx** [comment] 2017-09-05 19:47
@mitchellkrogza dont worry i be here

**Comment by mitchellkrogza** [comment] 2017-09-10 12:17
@xxcriticxx fresh raw links pushed out today, you will notice a sizeable decrease now due to a big removal of confirmed dead domains.

All false positives are now being controlled [through this CENTRAL REPO](https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects), so now every time I re-generate the hosts files, if any of the data sources I pull fresh data from happen to re-introduce any of the false-positives or whitelisted domains, they get stripped out at the end before the hosts files is generated and it's working like a charm so far.

This new centralized system is definitely the solution going forward to totally avoid any false positives from ever being re-added. So you can pull the fresh list into your pi-hole and keep reporting any more false positives you find 😉

**Comment by mitchellkrogza** [comment] 2017-09-10 12:19
Oh and of course a big thank you once again to @funilrys for his excellent funceble script which has proven itself without a shadow if a doubt to be the de-facto dead domain checker out there. 👍

**Closed** 2018-03-16 14:51 UTC
Labels: false positive
