### ISSUE TITLE
adobe-d.openx.net

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#451] opened 2018-09-13 11:02 UTC
needed to complete flash installation on windows  

Match found in https://hosts.ubuntu101.co.za/hosts:
   adobe-d.openx.net

test link:
https://get3.adobe.com/flashplayer/completion/adm/?exitcode=0&type=update&re=0&appId=200

![capture](https://user-images.githubusercontent.com/15007183/45484630-cb287f00-b722-11e8-8197-855711e607db.PNG)

**Comment by dnmTX** [comment] 2019-03-21 03:05
@xxcriticxx  `adobe-d.openx.net` is not blocked  but rather  `adobe-d.openx.net` is,in [@anudeepND's lists](https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt) for some reason.
I'll open a issue there and ask him.
See: https://github.com/anudeepND/blacklist/issues/40

**Comment by kowith337** [comment] 2019-03-21 05:44
To be clear by screenshot that Adobe use OpenX to suggest related products?

**Comment by dnmTX** [comment] 2019-03-21 06:58
@kowith337 i was thinking the same thing,and i'm pretty sure that blocking this domain in no way should interfere with the installation of Flash Player as it's showing up after just to (cough) promote (cough) some other products.

**Comment by dnmTX** [comment] 2019-03-21 17:02
@spirillen PISS OFF !!!!!!!! 🖕

**Comment by dnmTX** [comment] 2019-03-21 19:56
@funilrys,again,NOT FALSE POSITIVE. If @xxcriticxx is so eager to watch the ads after he downloads the Flash Player he can whitelisted on his end.The initial claim that brakes the installation is false.
You can close this.

**Comment by funilrys** [comment] 2019-03-22 17:24
Let's be clear on this one guys (and girls)! 

@dnmTX @spirillen: I think there are maybe problems between you two, but please stay respectful around this project. I do not caution disrespect. 

Some of you may think that this was whitelisted but: **NO**. It's just "On Hold" because I could not reproduce the presented behavior. 

You make me thought it was whitelisted because I was tired ... But actually *NO* guys/girls! I use the label `false positive` in order to filter review requests like this issue to others.

If you really want to talk about whitelisted domains, please let me know, I'll be glad to review and update the whitelist list.

Everything is in the Kanban project: https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/projects/1.

Let's stay peaceful, 
Let's stay respectful,
Cheers,

Nissar

**Closed by funilrys** 2019-03-22 17:24 UTC
Labels: false positive, high priority

**Comment by spirillen** [comment] 2019-03-22 20:57
Hi @funilrys you're right that `dnmTX` for some reason sees me as a red cloth, however I have actually no idea why.. 

So @dnmTX should we try to find back to each other in good behavior over a virtual cold :beer: ?
