### ISSUE TITLE
vod.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#334] opened 2018-05-27 11:49 UTC
back on the list same as #175 

Match found in list.34.hosts.ubuntu101.co.za.domains:
  
   vod.pl

**Comment by funilrys** [comment] 2018-05-27 11:51
Duplicate of #175 

______________
Closing + Reopening #175

**Closed by funilrys** 2018-05-27 11:51 UTC
